### ISSUE TITLE
json-schema validation for values-files

### ISSUE THREAD

**Issue by pantafive** [nixys/nxs-universal-chart#29]
I propose to create json-schema for values-files.

It is difficult to create a schema for all possible cases in one time. I propose to start from small example and update schema iteratively.

Whole workflow may look like this:

- [ ] create example schema
- [ ] create testing workflow
- [ ] integrate schema testing in CI with GitHub Actions
- [ ] publish schema to schemastore.org
- [ ] iteratively make schema bulletproof

If we want to engage community in this process, we should work in main branch - people will use half-baked schema and report their issues.

**Comment by artemdanielyan** [comment]
Hello, as I said in PR, json-schema is too restrictive for purposes of this helm-chart. Probably we will add some additional errors on templating level, but I keep in mind your approach, thank you!
