### ISSUE TITLE
GPLv3 is copyleft license

### ISSUE THREAD

**Issue by GRomR1** [nixys/nxs-universal-chart#34]
Is it possible to change license to Apache 2.0?

Many open-source projects prefer exactly this type of licensing.

For example 

https://terminusdb.com/blog/we-love-gplv3-but-are-switching-license-to-apache-2-0-terminusdb/

**Comment by randreev1321** [comment]
Hi @GRomR1.

Thank you for your activity and suggestion. We will discuss with the team the possibility of switching to another license and give an answer in this issue.

**Comment by randreev1321** [comment]
After discussion, the team agreed to your suggestion. Is Apache2 suitable?

**Comment by randreev1321** [comment]
The licence update will take place in the next minor release.

**Comment by GRomR1** [comment]
@randreev1321 many thanks, i'll wait it

**Comment by randreev1321** [comment]
Hi, @GRomR1.

As you ask we updated the license to Apache2.0 in [release 2.2.0](https://github.com/nixys/nxs-universal-chart/releases/tag/v2.2.0).
