### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by GRomR1** [nixys/nxs-universal-chart#55]
I saw that new release was published yesterday but not any comments on the active issues. My PRs are open on a long time and no one ask me anything. 
I want to ask authors about yours plans to support the project. I have much ideas and I already realized them in my fork project. I want to share them and may be it will be useful to you.
If you have questions please write me to any messenger.

**Comment by GRomR1** [comment]
@statkashaman @artemdanielyan

**Comment by artemdanielyan** [comment]
Hello! I just added current roadmap of ongoing development. Also I'm going through all the issues and PR's. 

Sorry, that it took much time,  we was fixing bugs lately. 

I need to test it first on many our installations to not break anything. Next week I will finish testing and accept your PR's. If I will have any questions, I will contact you on Telegram. 

My contacts also on README now, so we can stay in touch on all topics regarding this Chart.
